#!/usr/bin/env python3

import glob
import re
import logging
import shutil
import os

from tsg.intermediate import generate_intermediate
from tsg.config import PARSED_DIR, INTERMEDIATE_DIR

logging.basicConfig(level=logging.INFO)


def main():
#    shutil.rmtree(INTERMEDIATE_DIR)
#    os.mkdir(INTERMEDIATE_DIR)

    files = glob.glob(PARSED_DIR + '*.json')
    for f in files:
        try:
            uuid = re.search('([^/]*).json$', f).groups()[0]
        except AttributeError:
            continue

        generate_intermediate(uuid)


if __name__ == "__main__":
    main()
