#!/usr/bin/env python3

import logging

import pandas as pd

from tsg.config import RAW_DIR, PAGERANK_PATH
from tsg.indexer.page_rank import calc_page_rank

logging.basicConfig(level=logging.INFO)


def main():
    # get page rank
    page_rank_scores = calc_page_rank(RAW_DIR)

    # convert to dataframe
    df = pd.DataFrame.from_dict(page_rank_scores, orient='index')

    df.columns = ['pagerank_score']
    df.index.name = 'uuid'

    df.to_csv(PAGERANK_PATH)


if __name__ == "__main__":
    main()
