#!/usr/bin/env python3

import glob
import re
import logging

from tsg.indexer import create_index
from tsg.config import RAW_DIR, PARSED_DIR, INTERMEDIATE_DIR,\
    DICTIONARY_PATH, INDEXINFO_PATH, PAGERANK_PATH, QSCORE_PATH

logging.basicConfig(level=logging.INFO)


def main():

    num_documents = len(glob.glob(RAW_DIR+'*.html'))

    print('Careful, this deletes the index. Wanna proceed? y/N')
    if input() != 'y':
        return

    create_index(INTERMEDIATE_DIR,
                 PARSED_DIR,
                 num_documents,
                 DICTIONARY_PATH,
                 INDEXINFO_PATH,
                 QSCORE_PATH,
                 PAGERANK_PATH)


if __name__ == "__main__":
    main()
