#!/usr/bin/env python3

import glob
import re
import logging
import shutil
import os

from tsg.parser import parse_document
from tsg.config import RAW_DIR, PARSED_DIR

logging.basicConfig(level=logging.INFO)


def main():

    shutil.rmtree(PARSED_DIR)
    os.mkdir(PARSED_DIR)

    files = glob.glob(RAW_DIR + '*.html')
    for f in files:
        try:
            document_type = re.search('([^/_]*)[^/]*.html$', f).groups()[0]
        except AttributeError:
            continue

        parse_document(document_type, f)


if __name__ == "__main__":
    main()
