#!/usr/bin/env python3

import sys
from pprint import pprint

from tsg.search import search
from tsg.config import DICTIONARY_PATH, INDEXINFO_PATH


if len(sys.argv) == 1:
    print('Usage: {} <query string>'.format(sys.argv[0]))
    sys.exit(1)
else:
    query = " ".join(sys.argv[1:])
    results = search(query, DICTIONARY_PATH, INDEXINFO_PATH)
    pprint(results)
