#!/usr/bin/env python3
import logging

from tsg.frontend import app


logging.basicConfig(level=logging.INFO)


def main():
    app.run(host='0.0.0.0', port=8910)

if __name__ == "__main__":
    main()
